# Generated by Django 2.2.6 on 2019-10-31 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_type',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
