# Generated by Django 2.2.6 on 2019-11-01 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_car_type_car_type_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_image',
            field=models.ImageField(blank=True, default='default_car.jpg', upload_to='car_images'),
        ),
    ]
